- hosts: all
  roles:
    - role: ssh-hardening
      become: yes
      become_user: root
      become_method: sudo

      network_ipv6_enable: true
      ssh_permit_tunnel: true
      ssh_print_motd: true
      sftp_enabled: true
      ssh_banner: true
      ssh_use_dns: true
      sftp_chroot: false
      ssh_client_password_login: true
      ssh_listen_to: ['0.0','::']
